### ISSUE TITLE
Marina onboarding

### ISSUE THREAD

**Issue by gmyenni** [weecology/wiki#1]
#### Get set up on Lab Communication Platforms
 
- [x] Ask Glenda to show you where your copy of the onboarding checklist is on GitHub and how to check off completed tasks.
- [x] If you need a computer, tell Glenda if you want a laptop or desktop, and whether you want a windows, mac, or linux machine, and she will find you an available computer. Keep in mind that this computer is university property. It's assigned to you for work/educational purposes and when you end your official association with the lab, your computer will have to stay with us.
- [x] Check that Glenda has set you up on the weecology spaces for:
     - [x] GitHub
     - [x] Slack
- [x] Explore Weecology’s Slack group, sign up for any relevant channels
- [x] Take [Slack 101](https://slack.com/resources/slack-101) to learn slack basics
- [x] Take the [Markdown tutorial](https://www.markdowntutorial.com/). Markdown is a way of writing text that the computer then adds formatting to (i.e. italics, bullet points, headers). We use markdown for our website, as part of GitHub communication, and to create RMarkdown files to help keep track of projects.
 
#### Familiarize Yourself with Lab Culture and Values:

- [x] Read the [Way of Weecology](https://wiki.weecology.org/docs/lab-policy-procedures/way-of-weecology/)
- [x] Read the [Lab Code of Conduct](https://wiki.weecology.org/docs/lab-policy-procedures/code-of-conduct/)
- [x] Read the [Software Code of Conduct](https://wiki.weecology.org/docs/lab-policy-procedures/code-of-conduct-for-software/)

#### Familiarize Yourself about Lab Procedures:

- [x] Read lab policies about [Collaborating on GitHub](https://wiki.weecology.org/docs/computers-and-programming/git-collaboration/)
- [x] Read [Slack](https://wiki.weecology.org/docs/lab-policy-procedures/slack/)
- [x] Read the [Social Events](https://wiki.weecology.org/docs/lab-policy-procedures/social-events/) policy

#### Explore

- [x] Look at the Personnel Page on the Weecology website. Is there anyone on the active list that you haven’t met yet? Contact them and say hi. Maybe set up a video meeting or a coffee/tea/water break to chat.
- [x] Read through the Lab-Wiki sidebar. Read at least one page not linked to in the onboarding guide
 
#### Set Up Your Computer
 
- [x] Choose R and/or Python (you can always change or add the other later!). People in our groups use R and/or Python as their primary programming language. Most people use R, but if you have more serious software engineering or image processing plans in mind, talk to your advisor about Python. If in doubt, talk to your advisor or other lab members.
- [x] For R:
     - [x] [Download and Install R](https://cran.rstudio.com/). Site includes a windows, linux, and MacOS version. Windows users: you want the base install
     - [x] Download and Install [RStudio](https://rstudio.com/products/rstudio/download/#download). This is the Individual Development Environment (IDE) that we use for writing R code. Choose the free version.
- [ ] For Python:
    - [ ] Download and Install the [Anaconda Scientific Python Distribution](https://www.anaconda.com/products/individual)
    - [ ] Download and Install [Visual Studio Code](https://code.visualstudio.com/download) This is the Integrated Development Environment that we recommend for writing Python code. Windows users: choose ‘user installer’ and 64 bit
- [x] Install Git. Regardless of programming language you chose, do this. Git is the version control system we use for software and allows you to move things from your computer to GitHub. Follow the instructions on [Ethan’s course page](http://datacarpentry.org/semester-biology/computer-setup/) under the section “Git”. It has instructions for all three operating systems.
- [ ] Set up the link between your IDE and GitHub
     - [ ] [RStudio user instructions](https://wiki.weecology.org/docs/computers-and-programming/rstudio-git-integration/)
     - [ ] Visual Studio Code Users: Talk to Henry!
- [x] [Install Zotero](https://www.zotero.org/download/). This is the [reference manager](https://www.aje.com/arc/reference-manager-software-what-it-and-what-can-it-do/) preferred in the lab. It syncs with both Google Docs and Word. And is less likely to get into nasty fights with DropBox if you keep all your PDFs there.

- Optional: You can also install the [zotero connector](https://www.zotero.org/download/connectors) which is a browser plugin that allows you to download articles being viewed in your browser directly to your zotero library

- [x] Set up a file back-up service. Computers die. Laptops have accidents. Hurricanes happen. You don't want to lose all your work when one of these occurs. A way to back up your files (preferably without you having to think about it) is important. Pick and install one of the following on your computer. Set up that folder as your primary work folder.
     - [x] DropBox: is commonly used in the lab and has a [free account](https://www.dropbox.com/basic) with up to 2 GB of storage. Staff can have a free account with more storage [through UF](https://it.ufl.edu/services/dropbox-for-education).
     - [x] OneDrive: students also have access to “unlimited” storage on UF’s [OneDrive](https://cloud.it.ufl.edu/collaboration-tools/office-365/).
- [ ] Set up your computer to print to the lab printer. The lab printer is located in room 015 and accessible from the UFL network at 10.242.89.51. You may need to [download and install drivers](https://support.hp.com/us-en/drivers/selfservice/hp-color-laserjet-pro-mfp-m478-m479-series/19202514) before adding it as a printer in order for it to function properly.
- [x] Set up [access to the T: drive](https://wiki.weecology.org/docs/computers-and-programming/t-drive/). This is a shared drive for the lab, and can be used to store large files associated with your project.
- [x] If the UF VPN is not already on your computer, install the [Cisco AnyConnect VPN](https://it.ufl.edu/ict/documentation/network-infrastructure/vpn/). You'll need this to do literature searches from off campus.

Congratulations! You have gotten yourself prepared to start working with the group! You’re now ready for Stage 2 of Onboarding: Engaging with the Science and Tools.

#### Learn about the Lab Intellectual Space:

- [ ]  Work through the [Weecology reading list](https://wiki.weecology.org/docs/getting-started/lab-reading-list/). (note: the reading list is still in development). For each of the subject areas read the overview paper.
    - [x] Portal Project Overview
    - [ ] Macroecology Overview
    - [x] Forecasting Overview
    - [ ] IDEA
- [ ] Pick at least two areas that are especially interesting/relevant to you. Read all the papers listed on the reading list in that topic area
- [ ] Are you funded by a grant? Ask the grant PI (probably Ethan or Morgan) for a copy to read. Don't know if you're funded on a grant? Ask Ethan, Morgan, or Glenda (she knows everything).
- [ ] On the [lab website](https://weecology.org/), find a recent paper that looks interesting to you that is by someone currently in the group
     - [ ] Read the paper
     - [ ] Set up a meeting with that person to chat about their paper

#####  Learn about Git and GitHub.

- [ ] Go through the [Git for Humans](https://speakerdeck.com/alicebartlett/git-for-humans) slide show. It’s a good high-level introduction to what Git is and the jargon associated with it.
- [ ] Read [What Is GitHub? A Beginner’s Introduction to Github](https://kinsta.com/knowledgebase/what-is-github/). This will explain the relationship between Git and GitHub.
- [ ] Do a tutorial apply what you’ve just learned. Two good ones for practicing basic commands: [GitHub Tutorial](https://guides.github.com/activities/hello-world/) and/or [git and github for beginners](https://product.hubspot.com/blog/git-and-github-tutorial-for-beginners)
- [ ] Apply your markdown/Github knowledge:
     - [ ] Find a page on the lab wiki that has out of date info or has a typo
     - [ ] Fix that page.
     - [ ] Make a commit message before you save your changes
     - [ ] Identify a new page the lab wiki needs or a major change to an existing page (i.e. is there info you felt would be better moved onto one page? Something that should be added to the onboarding process? A page you wish existed?).
     - [ ] Create an issue in the [Lab Wiki](https://github.com/weecology/wiki) Repo that explains your proposed change/addition.

**Comment by ethanwhite** [comment]
@MarinaMarquis is off to other things, so closing
